site_name: Coal
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
  custom_dir: overrides
  logo: assets/logo.svg
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Language manual: language-manual.md
  - Data and codata: data-and-codata.md
  - License: license.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
