site_name: Coal
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Language manual: language-manual.md
