site_name: Coal
site_url: https://coal-lang.org/
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Language manual: language-manual.md
  - CLI reference: cli.md
  - Standard library: /standard-library/
  - Examples:
      - Quicksort: examples/quicksort.md
      - Basic I/O: examples/basic-io.md
      - Monads: examples/monads.md
      - Data structures: examples/data-structures.md
  - Packages: packages.md
  - Data and codata: data-and-codata.md
  - License: license.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: coal
          class: coal
          format: extensions.coal_shiki.coal_fence_format
          validator: extensions.coal_shiki.coal_fence_validator
  - extensions.coal_shiki
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
