site_name: Coal
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
  custom_dir: overrides
  logo: assets/logo.svg
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Language manual: language-manual.md
  - Data and codata: data-and-codata.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
