name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches: [ "main" ]     

permissions:
  contents: write           # required to push to gh-pages via actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          # add other mkdocs plugins you use, for example:
          # pip install mkdocs-awesome-pages-plugin
      - name: Build site
        run: mkdocs build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          # optional: keep history
          # keep_files: true
